databases:
  - name: learning_log
    plan: free
    databaseName: mysite
    user: learning_log

services:
  - type: web
    plan: free
    name: learning_log
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn learning_log.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: learning_logdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4