databases:
  - name: learninglog
    plan: free
    databaseName: learninglog_db
    user: Divesh

services:
  - type: web
    plan: free
    name: learninglog
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn learninglog_db.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: learninglog
          property: connectionString
      - key: django-insecure-bpyvp@^(hje^8m!5^vb!r!ocptcizetuxm#_2pe%2759l8sy0p
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4