databases:
  - name: learning_log
    plan: free
    databaseName: learning_logdb
    user: learning_log

services:
  - type: web
    plan: free
    name: learning_log
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn learning_log.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: learning_logdb
          property: connectionString
      - key: django-insecure-bpyvp@^(hje^8m!5^vb!r!ocptcizetuxm#_2pe%2759l8sy0p
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4